name: Publish Web

on:
  workflow_dispatch: {}

jobs:
  publish-web:
    name: Publish Web
    runs-on: ubuntu-latest
    container:
      image: barichello/godot-ci:3.4.4
    steps:
      - uses: actions/checkout@v2
        with:
          lfs: true
      - run: ./scripts/ci/prepare-templates.sh
      - run: ./scripts/ci/build-channel.sh web
      - run: apt-get update && apt-get install -y rsync
      - uses: JamesIves/github-pages-deploy-action@v4.2.5
        with:
          BRANCH: gh-pages
          FOLDER: build/web
